name: findNP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.25.0
  - jupyter=1.0.0
  - lhapdf=6.5.4
  - matplotlib=3.8.0
  - numpy=1.26.3
  - pandas=2.1.4
  - pip=23.3.1
  - python=3.10.13
  - pytorch=2.3.0
  - scikit-learn=1.4.2
  - scipy=1.11.4
  - seaborn=0.12.2
  - pip:
      - corner==2.2.2
      - cython==3.0.8
      - ultranest==3.6.4

